tmp/package-mdapi-check/objects/NF_Form__c.object
<CustomObject>
    <description>Stable business identity for a TwinaForms form.</description>
    <label>NF Form</label>
    <nameField>
        <displayFormat>FORM-{0000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NF Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Current_Draft_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current draft version for the form.</description>
        <inlineHelpText>Points to the version currently being edited.</inlineHelpText>
        <label>Current Draft Version</label>
        <referenceTo>NF_Form_Version__c</referenceTo>
        <relationshipLabel>Forms as Current Draft</relationshipLabel>
        <relationshipName>FormsAsCurrentDraft</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Published_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current published version for the form.</description>
        <inlineHelpText>Points to the live published version.</inlineHelpText>
        <label>Current Published Version</label>
        <referenceTo>NF_Form_Version__c</referenceTo>
        <relationshipLabel>Forms as Current Published</relationshipLabel>
        <relationshipName>FormsAsCurrentPublished</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Internal description or notes about the form.</description>
        <inlineHelpText>Internal description or notes.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NF_Key__c</fullName>
        <description>Unique internal key for the form.</description>
        <inlineHelpText>Stable internal or business key for the form.</inlineHelpText>
        <label>NF Key</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned project for organizing the form in the Designer.</description>
        <label>Project</label>
        <referenceTo>NF_Project__c</referenceTo>
        <relationshipLabel>Project Forms</relationshipLabel>
        <relationshipName>ProjectForms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned reusable theme for the form.</description>
        <label>Theme</label>
        <referenceTo>NF_Theme__c</referenceTo>
        <relationshipLabel>Themed Forms</relationshipLabel>
        <relationshipName>ThemedForms</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

tmp/package-mdapi-check/objects/NF_Form_Action__c.object
<CustomObject>
    <description>Server-side executable form actions for a TwinaForms form version.</description>
    <label>NF Form Action</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NF Form Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Version__c</fullName>
        <description>Parent form version for this action.</description>
        <inlineHelpText>Form version that owns this action.</inlineHelpText>
        <label>Form Version</label>
        <referenceTo>NF_Form_Version__c</referenceTo>
        <relationshipLabel>Form Actions</relationshipLabel>
        <relationshipName>FormActions</relationshipName>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

tmp/package-mdapi-check/objects/NF_Form_Element__c.object
<CustomObject>
    <description>UI and layout elements for a TwinaForms form version.</description>
    <label>NF Form Element</label>
    <nameField>
        <displayFormat>ELM-{0000}</displayFormat>
        <label>Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NF Form Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form_Version__c</fullName>
        <description>Parent form version for this element.</description>
        <inlineHelpText>Form version that owns this element.</inlineHelpText>
        <label>Form Version</label>
        <referenceTo>NF_Form_Version__c</referenceTo>
        <relationshipLabel>Form Elements</relationshipLabel>
        <relationshipName>FormElements</relationshipName>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

tmp/package-mdapi-check/objects/NF_Form_Publication__c.object
<CustomObject>
    <description>Operational publication history for a TwinaForms form version.</description>
    <label>NF Form Publication</label>
    <nameField>
        <displayFormat>PUB-{0000}</displayFormat>
        <label>Publication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NF Form Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Form associated with this publication record.</description>
        <inlineHelpText>Related form.</inlineHelpText>
        <label>Form</label>
        <referenceTo>NF_Form__c</referenceTo>
        <relationshipLabel>Form Publications</relationshipLabel>
        <relationshipName>FormPublications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Form version associated with this publication record.</description>
        <inlineHelpText>Related form version.</inlineHelpText>
        <label>Form Version</label>
        <referenceTo>NF_Form_Version__c</referenceTo>
        <relationshipLabel>Version Publications</relationshipLabel>
        <relationshipName>VersionPublications</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

tmp/package-mdapi-check/objects/NF_Form_Version__c.object
<CustomObject>
    <description>Versioned publishable snapshot of a TwinaForms form.</description>
    <label>NF Form Version</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NF Form Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Form__c</fullName>
        <description>Parent form for this version.</description>
        <inlineHelpText>Parent form record.</inlineHelpText>
        <label>Form</label>
        <referenceTo>NF_Form__c</referenceTo>
        <relationshipLabel>Form Versions</relationshipLabel>
        <relationshipName>FormVersions</relationshipName>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version_Number__c</fullName>
        <description>Numeric version number.</description>
        <inlineHelpText>Version number for this form version.</inlineHelpText>
        <label>Version Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

tmp/package-mdapi-check/objects/NF_Project__c.object
<CustomObject>
    <description>Top-level TwinaForms grouping for related forms.</description>
    <label>NF Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NF Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <description>Optional admin-facing context for the project.</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

tmp/package-mdapi-check/objects/NF_Theme__c.object
<CustomObject>
    <description>Reusable TwinaForms theme definition assigned to forms.</description>
    <label>NF Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NF Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Background_Color__c</fullName>
        <label>Background Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Button_Background_Color__c</fullName>
        <label>Button Background Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Button_Font__c</fullName>
        <label>Button Font</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Button_Font_Size_Px__c</fullName>
        <label>Button Font Size Px</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Button_Text_Color__c</fullName>
        <label>Button Text Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Form_Background_Color__c</fullName>
        <label>Form Background Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Border_Color__c</fullName>
        <label>Form Border Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Width__c</fullName>
        <label>Form Width</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hint_Text_Color__c</fullName>
        <label>Hint Text Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Input_Background_Color__c</fullName>
        <label>Input Background Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Input_Border_Color__c</fullName>
        <label>Input Border Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Input_Border_Radius_Px__c</fullName>
        <label>Input Border Radius Px</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Logo_URL__c</fullName>
        <label>Logo URL</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Main_Font__c</fullName>
        <label>Main Font</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Text_Color__c</fullName>
        <label>Main Text Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Text_Size_Px__c</fullName>
        <label>Main Text Size Px</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section_Title_Font__c</fullName>
        <label>Section Title Font</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_Title_Font_Size_Px__c</fullName>
        <label>Section Title Font Size Px</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section_Title_Text_Color__c</fullName>
        <label>Section Title Text Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Font__c</fullName>
        <label>Title Font</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Font_Size_Px__c</fullName>
        <label>Title Font Size Px</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title_Text_Color__c</fullName>
        <label>Title Text Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/NativeFormsTestDataFactory.cls
@IsTest
public class NativeFormsTestDataFactory {
    private static Integer sequence = 1;

    private static Integer nextSequence() {
        Integer current = sequence;
        sequence += 1;
        return current;
    }

    public static NF_Project__c buildProject(String name) {
        return new NF_Project__c(
            Name = name
        );
    }

    public static NF_Project__c createProject(String name) {
        NF_Project__c projectRecord = buildProject(name);
        insert projectRecord;
        return [
            SELECT Id, Name, Description__c
            FROM NF_Project__c
            WHERE Id = :projectRecord.Id
        ];
    }

    public static NF_Theme__c createTheme(String name) {
        Integer current = nextSequence();
        NF_Theme__c themeRecord = new NF_Theme__c(
            Name = String.isBlank(name) ? 'Test Theme ' + current : name
        );
        insert themeRecord;
        return [
            SELECT Id, Name, Logo_URL__c, Form_Width__c, Background_Color__c, Form_Background_Color__c, Form_Border_Color__c,
                   Title_Font__c, Title_Font_Size_Px__c, Title_Text_Color__c,
                   Section_Title_Font__c, Section_Title_Font_Size_Px__c, Section_Title_Text_Color__c,
                   Main_Font__c, Main_Text_Size_Px__c, Main_Text_Color__c, Hint_Text_Color__c,
                   Input_Border_Radius_Px__c, Input_Background_Color__c, Input_Border_Color__c,
                   Button_Font__c, Button_Font_Size_Px__c, Button_Text_Color__c, Button_Background_Color__c
            FROM NF_Theme__c
            WHERE Id = :themeRecord.Id
        ];
    }

    public static NF_Form__c buildForm(String descriptionValue) {
        return buildForm(descriptionValue, null, null);
    }

    public static NF_Form__c buildForm(String descriptionValue, Id projectId) {
        return buildForm(descriptionValue, projectId, null);
    }

    public static NF_Form__c buildForm(String descriptionValue, Id projectId, String formKey) {
        NF_Form__c formRecord = new NF_Form__c(
            Description__c = descriptionValue
        );
        if (projectId != null) {
            formRecord.Project__c = projectId;
        }
        if (String.isNotBlank(formKey)) {
            formRecord.NF_Key__c = formKey;
        }
        return formRecord;
    }

    public static NF_Form__c createForm(String descriptionValue) {
        return createForm(descriptionValue, null, null);
    }

    public static NF_Form__c createForm(String descriptionValue, Id projectId) {
        return createForm(descriptionValue, projectId, null);
    }

    public static NF_Form__c createForm(String descriptionValue, Id projectId, String formKey) {
        NF_Form__c formRecord = buildForm(descriptionValue, projectId, formKey);
        insert formRecord;
        return [
            SELECT Id, Description__c, NF_Key__c, Project__c, Project__r.Name, Theme__c,
                   Current_Draft_Version__c, Current_Published_Version__c
            FROM NF_Form__c
            WHERE Id = :formRecord.Id
        ];
    }

    public static NF_Form_Version__c createDraftVersion(Id formId) {
        return createVersion(formId, 1, 'Draft', 'Never Published', NativeFormsTestConfigFactory.basicUiSettingsJson());
    }

    public static NF_Form_Version__c createVersion(
        Id formId,
        Decimal versionNumber,
        String versionStatus,
        String publishStatus,
        String uiSettingsJson
    ) {
        NF_Form_Version__c versionRecord = new NF_Form_Version__c(
            Form__c = formId,
            Version_Number__c = versionNumber == null ? 1 : versionNumber,
            Version_Status__c = String.isBlank(versionStatus) ? 'Draft' : versionStatus,
            Publish_Status__c = String.isBlank(publishStatus) ? 'Never Published' : publishStatus,
            Security_Mode__c = 'secure-edit',
            Prefill_Params_JSON__c = '[]',
            UI_Settings_JSON__c = String.isBlank(uiSettingsJson) ? NativeFormsTestConfigFactory.basicUiSettingsJson() : uiSettingsJson
        );
        insert versionRecord;
        return [
            SELECT Id, Name, Form__c, Version_Number__c, Version_Status__c, Publish_Status__c,
                   Security_Mode__c, Prefill_Params_JSON__c, UI_Settings_JSON__c, Custom_JS__c
            FROM NF_Form_Version__c
            WHERE Id = :versionRecord.Id
        ];
    }

    public static NF_Form__c assignCurrentVersions(Id formId, Id currentDraftVersionId, Id currentPublishedVersionId) {
        update new NF_Form__c(
            Id = formId,
            Current_Draft_Version__c = currentDraftVersionId,
            Current_Published_Version__c = currentPublishedVersionId
        );
        return [
            SELECT Id, Description__c, NF_Key__c, Project__c, Project__r.Name, Theme__c,
                   Current_Draft_Version__c, Current_Published_Version__c
            FROM NF_Form__c
            WHERE Id = :formId
        ];
    }

    public static NF_Form_Element__c createElement(
        Id versionId,
        String elementType,
        String label,
        String fieldKey,
        Integer elementIndex,
        Integer orderValue,
        String configJson,
        String parentElementId
    ) {
        Integer current = nextSequence();
        NF_Form_Element__c elementRecord = new NF_Form_Element__c(
            Form_Version__c = versionId,
            Element_Id__c = String.valueOf(elementType).toLowerCase() + '-' + current,
            Element_Type__c = elementType,
            Label__c = String.isBlank(label) ? 'Element ' + current : label,
            Field_Key__c = fieldKey,
            Element_Index__c = elementIndex == null ? current : elementIndex,
            Order__c = orderValue == null ? current * 10 : orderValue,
            Config_JSON__c = String.isBlank(configJson) ? '{}' : configJson,
            Parent_Element_Id__c = parentElementId
        );
        insert elementRecord;
        return [
            SELECT Id, Element_Id__c, Element_Type__c, Label__c, Field_Key__c, Element_Index__c,
                   Order__c, Config_JSON__c, Parent_Element_Id__c
            FROM NF_Form_Element__c
            WHERE Id = :elementRecord.Id
        ];
    }

    public static NF_Form_Action__c createAction(
        Id versionId,
        String actionScope,
        String objectApiName,
        String commandKey,
        String storeResultAs,
        String commandType,
        Integer orderValue,
        String configJson
    ) {
        Integer current = nextSequence();
        NF_Form_Action__c actionRecord = new NF_Form_Action__c(
            Form_Version__c = versionId,
            Action_Scope__c = String.isBlank(actionScope) ? 'Prefill' : actionScope,
            Object_Api_Name__c = objectApiName,
            Command_Key__c = String.isBlank(commandKey) ? 'action' + current : commandKey,
            Store_Result_As__c = storeResultAs,
            Command_Type__c = commandType,
            Order__c = orderValue == null ? current * 10 : orderValue,
            Config_JSON__c = String.isBlank(configJson) ? '{}' : configJson
        );
        insert actionRecord;
        return [
            SELECT Id, Form_Version__c, Action_Scope__c, Object_Api_Name__c, Command_Key__c,
                   Store_Result_As__c, Command_Type__c, Order__c, Config_JSON__c
            FROM NF_Form_Action__c
            WHERE Id = :actionRecord.Id
        ];
    }

    public static NF_Form_Publication__c createPublication(
        Id formId,
        Id versionId,
        String publicationStatus,
        String generatedHtmlRef
    ) {
        return createPublication(formId, versionId, publicationStatus, generatedHtmlRef, null);
    }

    public static NF_Form_Publication__c createPublication(
        Id formId,
        Id versionId,
        String publicationStatus,
        String generatedHtmlRef,
        String publishedFormId
    ) {
        NF_Form_Publication__c publicationRecord = new NF_Form_Publication__c(
            Form__c = formId,
            Form_Version__c = versionId,
            Publication_Status__c = String.isBlank(publicationStatus) ? 'Success' : publicationStatus,
            Generated_HTML_Ref__c = generatedHtmlRef,
            Published_Form_Id__c = publishedFormId,
            Published_At__c = System.now()
        );
        insert publicationRecord;
        return [
            SELECT Id, Form__c, Form_Version__c, Publication_Status__c, Generated_HTML_Ref__c, Published_Form_Id__c, Published_At__c
            FROM NF_Form_Publication__c
            WHERE Id = :publicationRecord.Id
        ];
    }

    public static List<Contact> createContacts(Integer countValue) {
        Integer safeCount = countValue == null || countValue < 0 ? 0 : countValue;
        List<Contact> contacts = new List<Contact>();
        for (Integer indexValue = 0; indexValue < safeCount; indexValue += 1) {
            Integer current = nextSequence();
            contacts.add(new Contact(
                LastName = 'NativeForms Test Contact ' + current,
                Email = 'nativeforms-test-' + current + '@example.com'
            ));
        }
        if (!contacts.isEmpty()) {
            insert contacts;
        }
        return contacts;
    }

    public static User createActiveUser(String firstNameValue, String lastNameValue) {
        Integer current = nextSequence();
        String safeFirstName = String.isBlank(firstNameValue) ? 'NativeForms' : firstNameValue.trim();
        String safeLastName = String.isBlank(lastNameValue) ? 'Test User ' + current : lastNameValue.trim();
        String uniqueSuffix = String.valueOf(System.now().getTime()) + '-' + current;
        String emailLocalPart = 'nativeforms-user-' + current;

        User userRecord = new User(
            FirstName = safeFirstName,
            LastName = safeLastName,
            Alias = ('nf' + current).left(8),
            Email = emailLocalPart + '@example.com',
            Username = emailLocalPart + '+' + uniqueSuffix + '@example.com',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = UserInfo.getProfileId()
        );
        insert userRecord;
        return [
            SELECT Id, Name, Email, IsActive
            FROM User
            WHERE Id = :userRecord.Id
        ];
    }
}